---
- hosts: all
  become: true
  
  tasks:
    # - name: Print the gathered facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Stop the Ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when: 
        ansible_facts['os_family'] == "Debian"
        # ansible_facts['os_family'] == "RedHat"