--- 
- name: Provisioning an ec2 instance
  block:

  - name: Create security_group
    amazon.aws.ec2_security_group:
      name: "{{ security_group_name }}"
      description: "Security group for Ansible EC2 instance"
      region: "{{ aws_region }}"
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined 
      rules:
       - proto: tcp
         ports: 22
         cidr_ip: "0.0.0.0/0"
         rule_desc: "Allow SSH access from anywhere"
    register: sg_result


  - name: Import SSH key
    # Ensure the SSH key is present in AWS
    amazon.aws.ec2_key:
      name: "prod-ssh-key"
      region: "{{ aws_region }}"
      state: present
      key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined


  - name: Create ec2 instances with unique names and a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: "prod-ssh-key"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: "{{ type }}"
      security_group: "{{ sg_result.group_id }}"
      region: "{{ aws_region }}"
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
        Environment: Testing
    loop: "{{ instance_names }}"